#!/usr/bin/env bash
# Shared marketing version + integer build number for Apple targets.
#
#   MARKETING  host/VERSION (hand-bumped; tags are v$VERSION)
#   BUILD      git rev-list --count HEAD  (monotonic, same on every machine)
#
# Source this from other scripts (bash):
#   # shellcheck source=version-env.sh
#   source "$(dirname "$0")/version-env.sh"
#
# Or print for shell eval / CI:
#   eval "$(./scripts/version-env.sh --export)"
#
# Write macos/Version.xcconfig (picked up by XcodeGen configFiles):
#   ./scripts/version-env.sh --write-xcconfig
#
# Stamp a built Info.plist from an Xcode Run Script phase (needs
# TARGET_BUILD_DIR + INFOPLIST_PATH from xcodebuild):
#   ./scripts/version-env.sh --stamp-plist
set -euo pipefail

_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." && pwd)"
_VERSION_FILE="$_ROOT/host/VERSION"
_XCCONFIG="$_ROOT/macos/Version.xcconfig"

if [[ ! -f "$_VERSION_FILE" ]]; then
  echo "error: missing $_VERSION_FILE" >&2
  exit 1
fi

HEADROOM_VERSION="$(tr -d '[:space:]' < "$_VERSION_FILE")"
if [[ ! "$HEADROOM_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]]; then
  echo "error: host/VERSION must look like 1.2.3 (got '$HEADROOM_VERSION')" >&2
  exit 1
fi

HEADROOM_BUILD="$(git -C "$_ROOT" rev-list --count HEAD 2>/dev/null || true)"
if [[ -z "${HEADROOM_BUILD:-}" || ! "$HEADROOM_BUILD" =~ ^[0-9]+$ ]]; then
  HEADROOM_BUILD=0
fi

# Apple CFBundleVersion must be non-zero.
if [[ "$HEADROOM_BUILD" -lt 1 ]]; then
  HEADROOM_BUILD=1
fi

# Apple Developer team used to sign. Resolution order:
#   1. $HEADROOM_TEAM_ID in the environment (CI, release scripts)
#   2. DEVELOPMENT_TEAM in the gitignored macos/Local.xcconfig (see README,
#      "Signing as yourself") — parsed here so scripts that pass the team on
#      the xcodebuild command line agree with what Xcode reads
#   3. the maintainer's (Centaur Labs, the entity behind the App Store listing)
# Unsigned local builds ignore it entirely (scripts/build-app.sh passes
# CODE_SIGNING_ALLOWED=NO).
_LOCAL_XCCONFIG="$_ROOT/macos/Local.xcconfig"
_DEFAULT_TEAM_ID=992N457T8D
# Whether the caller set the env var is remembered separately: only then does
# the generated xcconfig pin the team after the Local.xcconfig include. In
# every other case the include must stay the last word, so an edit to
# Local.xcconfig takes effect on the next build without waiting for this
# script to regenerate a value it baked in earlier.
#
# That answer has to survive a process boundary. We export HEADROOM_TEAM_ID
# below, and sync-embedded-host.sh sources this file and then runs it again as
# a child — which inherits the export and cannot tell our own default from a
# team the caller asked for. It pinned every time, so on the one path
# contributors use (scripts/gen-project.sh) Local.xcconfig could never win.
# Carrying the provenance explicitly is what closes that: set-but-empty means
# "asked already, nobody set it", which is different from unset.
if [[ -n "${HEADROOM_TEAM_EXPLICIT+set}" ]]; then
  _TEAM_FROM_ENV="$HEADROOM_TEAM_EXPLICIT"
else
  _TEAM_FROM_ENV="${HEADROOM_TEAM_ID:+1}"
fi
if [[ -z "${HEADROOM_TEAM_ID:-}" && -f "$_LOCAL_XCCONFIG" ]]; then
  HEADROOM_TEAM_ID="$(sed -n 's|//.*||; s/^[[:space:]]*DEVELOPMENT_TEAM[[:space:]]*=[[:space:]]*//p' "$_LOCAL_XCCONFIG" | tail -n 1 | tr -d '[:space:]')"
fi
HEADROOM_TEAM_ID="${HEADROOM_TEAM_ID:-$_DEFAULT_TEAM_ID}"

export HEADROOM_VERSION HEADROOM_BUILD HEADROOM_TEAM_ID
export HEADROOM_TEAM_EXPLICIT="$_TEAM_FROM_ENV"

_write_xcconfig() {
  # Defaults first, the Local.xcconfig include last, so an edit there wins at
  # the moment Xcode reads it — not one regeneration later. Baking the
  # resolved team below the include would shadow a fresh Local.xcconfig with
  # a value this script resolved before that edit existed.
  cat > "$_XCCONFIG" <<EOF
// Generated by scripts/version-env.sh — do not edit. Personal overrides go in
// Local.xcconfig (gitignored), included last so its values win.
// MARKETING ← host/VERSION · BUILD ← git rev-list --count HEAD
MARKETING_VERSION = $HEADROOM_VERSION
CURRENT_PROJECT_VERSION = $HEADROOM_BUILD
DEVELOPMENT_TEAM = $_DEFAULT_TEAM_ID
HEADROOM_BUNDLE_PREFIX = com.centaur-labs
#include? "Local.xcconfig"
EOF
  # An explicit $HEADROOM_TEAM_ID outranks Local.xcconfig — that is how CI
  # and the release scripts sign — so only then is the team pinned after the
  # include. It re-resolves on every regeneration, and the callers that set
  # it regenerate as part of their run.
  if [[ -n "$_TEAM_FROM_ENV" ]]; then
    cat >> "$_XCCONFIG" <<EOF
// \$HEADROOM_TEAM_ID was set when this was generated; it outranks Local.xcconfig.
DEVELOPMENT_TEAM = $HEADROOM_TEAM_ID
EOF
  fi
}

_stamp_one() {
  local plist="$1"
  [[ -f "$plist" ]] || return 0
  # Set, or Add if Process Info.plist hasn't written the key yet.
  if ! /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $HEADROOM_VERSION" "$plist" 2>/dev/null; then
    /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $HEADROOM_VERSION" "$plist"
  fi
  if ! /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $HEADROOM_BUILD" "$plist" 2>/dev/null; then
    /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $HEADROOM_BUILD" "$plist"
  fi
  echo "stamped $plist → $HEADROOM_VERSION ($HEADROOM_BUILD)"
}

_stamp_plist() {
  if [[ -z "${TARGET_BUILD_DIR:-}" || -z "${INFOPLIST_PATH:-}" ]]; then
    echo "error: --stamp-plist needs TARGET_BUILD_DIR and INFOPLIST_PATH (Xcode build phase)" >&2
    exit 1
  fi
  local plist="${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
  if [[ ! -f "$plist" ]]; then
    echo "warning: Info.plist not found yet at $plist — skipping stamp" >&2
    return 0
  fi
  _stamp_one "$plist"
}

# Stamp the app Info.plist and any embedded appex — not every nested
# framework plist (those lack CFBundleShortVersionString and break Set).
_stamp_product() {
  if [[ -z "${TARGET_BUILD_DIR:-}" ]]; then
    echo "error: --stamp-product needs TARGET_BUILD_DIR" >&2
    exit 1
  fi
  if [[ -n "${INFOPLIST_PATH:-}" && -f "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}" ]]; then
    _stamp_one "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
  fi
  local product="${TARGET_BUILD_DIR}/${FULL_PRODUCT_NAME:-}"
  if [[ -d "$product" ]]; then
    _stamp_one "$product/Info.plist"
    local appex_plist
    for appex_plist in "$product"/PlugIns/*/Info.plist; do
      _stamp_one "$appex_plist"
    done
  fi
}


# Only parse CLI flags when this file is executed (not sourced). Sourcing from
# zsh sets $0 to this path and can leave stray $1 — never treat that as argv.
_executed=0
if [[ -n "${BASH_VERSION:-}" && "${BASH_SOURCE[0]}" == "$0" ]]; then
  _executed=1
fi

if [[ "$_executed" -eq 1 ]]; then
  case "${1:-}" in
    --export)
      printf 'export HEADROOM_VERSION=%q\n' "$HEADROOM_VERSION"
      printf 'export HEADROOM_BUILD=%q\n' "$HEADROOM_BUILD"
      ;;
    --print)
      echo "$HEADROOM_VERSION+$HEADROOM_BUILD"
      ;;
    --write-xcconfig)
      _write_xcconfig
      echo "wrote $_XCCONFIG ($HEADROOM_VERSION+$HEADROOM_BUILD)"
      ;;
    --stamp-plist)
      _stamp_plist
      ;;
    --stamp-product)
      _stamp_product
      ;;
    "" )
      echo "version $HEADROOM_VERSION  build $HEADROOM_BUILD"
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      echo "usage: $0 [--export|--print|--write-xcconfig|--stamp-plist|--stamp-product]" >&2
      exit 1
      ;;
  esac
fi
