#!/usr/bin/env bash
# Shared marketing version + integer build number for Apple targets.
#
#   MARKETING  host/VERSION (hand-bumped; tags are v$VERSION)
#   BUILD      git rev-list --count HEAD  (monotonic, same on every machine)
#
# Source this from other scripts (bash):
#   # shellcheck source=version-env.sh
#   source "$(dirname "$0")/version-env.sh"
#
# Or print for shell eval / CI:
#   eval "$(./scripts/version-env.sh --export)"
#
# Write macos/Version.xcconfig (picked up by XcodeGen configFiles):
#   ./scripts/version-env.sh --write-xcconfig
#
# Stamp a built Info.plist from an Xcode Run Script phase (needs
# TARGET_BUILD_DIR + INFOPLIST_PATH from xcodebuild):
#   ./scripts/version-env.sh --stamp-plist
set -euo pipefail

_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." && pwd)"
_VERSION_FILE="$_ROOT/host/VERSION"
_XCCONFIG="$_ROOT/macos/Version.xcconfig"

if [[ ! -f "$_VERSION_FILE" ]]; then
  echo "error: missing $_VERSION_FILE" >&2
  exit 1
fi

HEADROOM_VERSION="$(tr -d '[:space:]' < "$_VERSION_FILE")"
if [[ ! "$HEADROOM_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]]; then
  echo "error: host/VERSION must look like 1.2.3 (got '$HEADROOM_VERSION')" >&2
  exit 1
fi

HEADROOM_BUILD="$(git -C "$_ROOT" rev-list --count HEAD 2>/dev/null || true)"
if [[ -z "${HEADROOM_BUILD:-}" || ! "$HEADROOM_BUILD" =~ ^[0-9]+$ ]]; then
  HEADROOM_BUILD=0
fi

# Apple CFBundleVersion must be non-zero.
if [[ "$HEADROOM_BUILD" -lt 1 ]]; then
  HEADROOM_BUILD=1
fi

export HEADROOM_VERSION HEADROOM_BUILD

_write_xcconfig() {
  cat > "$_XCCONFIG" <<EOF
// Generated by scripts/version-env.sh — do not edit.
// MARKETING ← host/VERSION · BUILD ← git rev-list --count HEAD
MARKETING_VERSION = $HEADROOM_VERSION
CURRENT_PROJECT_VERSION = $HEADROOM_BUILD
EOF
}

_stamp_one() {
  local plist="$1"
  [[ -f "$plist" ]] || return 0
  # Set, or Add if Process Info.plist hasn't written the key yet.
  if ! /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $HEADROOM_VERSION" "$plist" 2>/dev/null; then
    /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $HEADROOM_VERSION" "$plist"
  fi
  if ! /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $HEADROOM_BUILD" "$plist" 2>/dev/null; then
    /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $HEADROOM_BUILD" "$plist"
  fi
  echo "stamped $plist → $HEADROOM_VERSION ($HEADROOM_BUILD)"
}

_stamp_plist() {
  if [[ -z "${TARGET_BUILD_DIR:-}" || -z "${INFOPLIST_PATH:-}" ]]; then
    echo "error: --stamp-plist needs TARGET_BUILD_DIR and INFOPLIST_PATH (Xcode build phase)" >&2
    exit 1
  fi
  local plist="${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
  if [[ ! -f "$plist" ]]; then
    echo "warning: Info.plist not found yet at $plist — skipping stamp" >&2
    return 0
  fi
  _stamp_one "$plist"
}

# Stamp the app Info.plist and any embedded appex — not every nested
# framework plist (those lack CFBundleShortVersionString and break Set).
_stamp_product() {
  if [[ -z "${TARGET_BUILD_DIR:-}" ]]; then
    echo "error: --stamp-product needs TARGET_BUILD_DIR" >&2
    exit 1
  fi
  if [[ -n "${INFOPLIST_PATH:-}" && -f "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}" ]]; then
    _stamp_one "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
  fi
  local product="${TARGET_BUILD_DIR}/${FULL_PRODUCT_NAME:-}"
  if [[ -d "$product" ]]; then
    _stamp_one "$product/Info.plist"
    local appex_plist
    for appex_plist in "$product"/PlugIns/*/Info.plist; do
      _stamp_one "$appex_plist"
    done
  fi
}


# Only parse CLI flags when this file is executed (not sourced). Sourcing from
# zsh sets $0 to this path and can leave stray $1 — never treat that as argv.
_executed=0
if [[ -n "${BASH_VERSION:-}" && "${BASH_SOURCE[0]}" == "$0" ]]; then
  _executed=1
fi

if [[ "$_executed" -eq 1 ]]; then
  case "${1:-}" in
    --export)
      printf 'export HEADROOM_VERSION=%q\n' "$HEADROOM_VERSION"
      printf 'export HEADROOM_BUILD=%q\n' "$HEADROOM_BUILD"
      ;;
    --print)
      echo "$HEADROOM_VERSION+$HEADROOM_BUILD"
      ;;
    --write-xcconfig)
      _write_xcconfig
      echo "wrote $_XCCONFIG ($HEADROOM_VERSION+$HEADROOM_BUILD)"
      ;;
    --stamp-plist)
      _stamp_plist
      ;;
    --stamp-product)
      _stamp_product
      ;;
    "" )
      echo "version $HEADROOM_VERSION  build $HEADROOM_BUILD"
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      echo "usage: $0 [--export|--print|--write-xcconfig|--stamp-plist|--stamp-product]" >&2
      exit 1
      ;;
  esac
fi
